'use client'

import { useMemo, useState } from 'react'
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Activity, AlertTriangle, Bell, CheckCircle2, ChevronRight, CircleDot, Clock3, FileText, Filter, Gauge, LayoutDashboard, Network, Play, Radar, Search, ShieldCheck, SlidersHorizontal, TrendingUp, Wifi, X } from 'lucide-react'

const traffic = [
  { time: '09:00', normal: 420, suspicious: 18 }, { time: '09:10', normal: 510, suspicious: 22 }, { time: '09:20', normal: 460, suspicious: 31 }, { time: '09:30', normal: 620, suspicious: 42 }, { time: '09:40', normal: 580, suspicious: 28 }, { time: '09:50', normal: 710, suspicious: 58 }, { time: '10:00', normal: 680, suspicious: 39 }, { time: '10:10', normal: 770, suspicious: 76 }, { time: '10:20', normal: 720, suspicious: 48 }, { time: '10:30', normal: 840, suspicious: 64 }, { time: '10:40', normal: 790, suspicious: 52 }, { time: '10:50', normal: 910, suspicious: 83 }, { time: '11:00', normal: 870, suspicious: 61 },
]
const protocols = [{ name: 'TCP', value: 62, color: '#38bdf8' }, { name: 'UDP', value: 24, color: '#818cf8' }, { name: 'ICMP', value: 9, color: '#f59e0b' }, { name: 'Other', value: 5, color: '#64748b' }]
const alerts = [
  { id: 'ALT-10428', type: 'Multi-port probing pattern', src: '192.0.2.44', dest: '198.51.100.20', protocol: 'TCP', severity: 'CRITICAL', risk: 92, time: '2 min ago', status: 'NEW' },
  { id: 'ALT-10427', type: 'Repeated failed connections', src: '203.0.113.17', dest: '198.51.100.8', protocol: 'TCP', severity: 'HIGH', risk: 78, time: '8 min ago', status: 'INVESTIGATING' },
  { id: 'ALT-10426', type: 'SYN-heavy connection behavior', src: '192.0.2.91', dest: '203.0.113.44', protocol: 'TCP', severity: 'HIGH', risk: 74, time: '14 min ago', status: 'NEW' },
  { id: 'ALT-10425', type: 'Unusual service-port activity', src: '198.51.100.63', dest: '192.0.2.10', protocol: 'UDP', severity: 'MEDIUM', risk: 56, time: '21 min ago', status: 'RESOLVED' },
  { id: 'ALT-10424', type: 'High connection rate', src: '203.0.113.28', dest: '198.51.100.31', protocol: 'TCP', severity: 'MEDIUM', risk: 48, time: '33 min ago', status: 'FALSE_POSITIVE' },
]

const severityClass: Record<string, string> = { CRITICAL: 'critical', HIGH: 'high', MEDIUM: 'medium', LOW: 'low' }

function StatCard({ label, value, icon: Icon, trend, tone }: { label: string; value: string; icon: typeof Activity; trend?: string; tone?: string }) {
  return <div className="stat-card"><div className={`stat-icon ${tone || ''}`}><Icon size={18} /></div><div><p>{label}</p><strong>{value}</strong>{trend && <span className="trend"><TrendingUp size={12} /> {trend}</span>}</div></div>
}

export default function Page() {
  const [activeNav, setActiveNav] = useState('Overview')
  const [selected, setSelected] = useState<(typeof alerts)[number] | null>(alerts[0])
  const [isRunning, setIsRunning] = useState(true)
  const [filterOpen, setFilterOpen] = useState(false)
  const [status, setStatus] = useState('NEW')
  const [toast, setToast] = useState('')
  const filteredAlerts = useMemo(() => alerts.filter((a) => status === 'ALL' || a.status === status || status === 'NEW'), [status])

  function simulate() { setToast('Synthetic flow injected — IDS rules re-evaluated'); setTimeout(() => setToast(''), 3000) }

  return <main className="ids-shell">
    <aside className="sidebar">
      <div className="brand"><div className="brand-mark"><ShieldCheck size={20} /></div><div><b>Sentinel<span>//</span>Flow</b><small>NETWORK DEFENSE</small></div></div>
      <div className="workspace"><span className="status-dot" /> <span>LAB ENVIRONMENT</span><ChevronRight size={14} /></div>
      <nav className="nav"><p className="nav-label">MONITORING</p>{[['Overview', LayoutDashboard], ['Live traffic', Wifi], ['Alerts', Bell], ['Investigations', Search]].map(([label, Icon]) => <button key={label as string} className={activeNav === label ? 'active' : ''} onClick={() => setActiveNav(label as string)}><Icon size={17} />{label as string}{label === 'Alerts' && <em>12</em>}</button>)}<p className="nav-label">ANALYSIS</p>{[['Detection rules', SlidersHorizontal], ['Network map', Network], ['Reports', FileText]].map(([label, Icon]) => <button key={label as string} className={activeNav === label ? 'active' : ''} onClick={() => setActiveNav(label as string)}><Icon size={17} />{label as string}</button>)}</nav>
      <div className="sidebar-bottom"><div className="engine-card"><div className="engine-title"><CircleDot size={13} /> DETECTION ENGINE <span>v2.4.1</span></div><strong><i /> Operational</strong><p>Last sync 11:02:48 UTC</p></div><div className="profile"><div className="avatar">AS</div><div><b>Alex Smith</b><small>SOC Analyst</small></div><ChevronRight size={15} /></div></div>
    </aside>
    <section className="content">
      <header className="topbar"><div><div className="crumb">SECURITY OPERATIONS <ChevronRight size={12} /> {activeNav.toUpperCase()}</div><h1>{activeNav === 'Overview' ? 'Network overview' : activeNav}</h1></div><div className="top-actions"><div className="live-pill"><span className={isRunning ? 'pulse' : ''} /> {isRunning ? 'LIVE SIMULATION' : 'SIMULATION PAUSED'}</div><button className="icon-button" aria-label="Notifications"><Bell size={18} /><i /></button><button className="user-chip">AS</button></div></header>
      <div className="dashboard">
        <div className="banner"><div className="banner-icon"><Radar size={22} /></div><div><b>Hybrid detection is active</b><p>Rules, anomaly scoring, and ML enrichment are evaluating synthetic flow records.</p></div><button onClick={() => setIsRunning(!isRunning)} className="banner-action">{isRunning ? 'Pause' : 'Resume'} <Play size={13} /></button></div>
        <div className="stats-grid"><StatCard label="Network flows" value="18,642" trend="12.8%" icon={Activity} tone="blue" /><StatCard label="Suspicious traffic" value="1,284" trend="8.4%" icon={AlertTriangle} tone="amber" /><StatCard label="Open alerts" value="24" icon={Bell} tone="red" /><StatCard label="Average risk score" value="42.7" trend="3.1%" icon={Gauge} tone="purple" /></div>
        <div className="section-heading"><div><h2>Detection telemetry</h2><p>Traffic volume and classification across the last 2 hours</p></div><div className="heading-actions"><button onClick={simulate} className="simulate"><Activity size={14} /> Simulate flow</button><button onClick={() => setFilterOpen(!filterOpen)} className="filter-button"><Filter size={14} /> Filters</button></div></div>
        {filterOpen && <div className="filter-row"><span>View:</span>{['ALL', 'NEW', 'INVESTIGATING', 'RESOLVED'].map((item) => <button key={item} className={status === item ? 'selected' : ''} onClick={() => setStatus(item)}>{item}</button>)}<button onClick={() => setFilterOpen(false)} aria-label="Close filters"><X size={14} /></button></div>}
        <div className="charts-grid"><div className="panel traffic-panel"><div className="panel-head"><div><h3>Flow activity</h3><span><i className="legend-blue" /> Normal <i className="legend-red" /> Suspicious</span></div><select aria-label="Time range"><option>Last 2 hours</option><option>Last 24 hours</option></select></div><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><AreaChart data={traffic}><defs><linearGradient id="normal" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#38bdf8" stopOpacity={0.28}/><stop offset="100%" stopColor="#38bdf8" stopOpacity={0}/></linearGradient><linearGradient id="suspicious" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#fb7185" stopOpacity={0.25}/><stop offset="100%" stopColor="#fb7185" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="#233044" vertical={false}/><XAxis dataKey="time" tick={{fill:'#718096',fontSize:11}} axisLine={false} tickLine={false}/><YAxis tick={{fill:'#718096',fontSize:11}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{background:'#111b2a',border:'1px solid #28384d',borderRadius:8,color:'#e7edf6'}}/><Area type="monotone" dataKey="normal" stroke="#38bdf8" fill="url(#normal)" strokeWidth={2}/><Area type="monotone" dataKey="suspicious" stroke="#fb7185" fill="url(#suspicious)" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></div><div className="panel protocol-panel"><div className="panel-head"><div><h3>Protocol distribution</h3><span>18,642 total flows</span></div><button className="more">•••</button></div><div className="donut"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={protocols} dataKey="value" nameKey="name" innerRadius={58} outerRadius={78} paddingAngle={3} stroke="none">{protocols.map((entry) => <Cell key={entry.name} fill={entry.color}/>)}</Pie><Tooltip contentStyle={{background:'#111b2a',border:'1px solid #28384d',borderRadius:8}} /></PieChart></ResponsiveContainer><div><strong>18.6k</strong><span>flows</span></div></div><div className="protocol-legend">{protocols.map(p => <div key={p.name}><span style={{background:p.color}} />{p.name}<b>{p.value}%</b></div>)}</div></div></div>
        <div className="section-heading alerts-heading"><div><h2>Recent alerts</h2><p>Prioritized detections requiring analyst attention</p></div><button className="view-all">View all alerts <ChevronRight size={14} /></button></div>
        <div className="alert-layout"><div className="panel alert-table"><div className="table-head"><span>ALERT</span><span>SOURCE / DESTINATION</span><span>SEVERITY</span><span>RISK</span><span>STATUS</span><span /></div>{filteredAlerts.map(alert => <button className={`alert-row ${selected?.id === alert.id ? 'row-selected' : ''}`} key={alert.id} onClick={() => { setSelected(alert); setStatus(alert.status) }}><div className="alert-name"><span className={`severity-bar ${severityClass[alert.severity]}`} /><div><b>{alert.type}</b><small>{alert.id} · {alert.time}</small></div></div><div className="endpoints"><span>{alert.src}</span><ChevronRight size={12}/><span>{alert.dest}</span><small>{alert.protocol}</small></div><span className={`severity ${severityClass[alert.severity]}`}>{alert.severity}</span><strong className="risk">{alert.risk}<small>/100</small></strong><span className={`status ${alert.status.toLowerCase()}`}>{alert.status.replace('_', ' ')}</span><ChevronRight size={15} className="row-chevron" /></button>)}</div>
          {selected && (<div className="panel detail-panel"><div className="detail-head"><div><span className={`severity ${severityClass[selected.severity]}`}>{selected.severity}</span><h3>Alert details</h3></div><button onClick={() => setSelected(null)} aria-label="Close detail"><X size={16}/></button></div><div className="detail-id">{selected.id}<span>{selected.time}</span></div><div className="detail-risk"><div><span>FINAL RISK SCORE</span><strong>{selected.risk}<small>/100</small></strong></div><div className="risk-ring" style={{'--risk': `${selected.risk * 3.6}deg`} as React.CSSProperties}><span>{selected.risk}</span></div></div><div className="detail-grid"><div><label>SOURCE</label><b>{selected.src}</b></div><div><label>DESTINATION</label><b>{selected.dest}</b></div><div><label>PROTOCOL</label><b>{selected.protocol}</b></div><div><label>DETECTION</label><b>IDS-00{selected.id.slice(-1)}</b></div></div><div className="reason"><AlertTriangle size={15}/><div><b>Why this fired</b><p>{selected.type} crossed the configured detection baseline. This is a synthetic event for investigation training.</p></div></div><label className="status-label">UPDATE STATUS</label><select value={selected.id === alerts[0].id ? status : selected.status} onChange={(e) => setStatus(e.target.value)}><option>NEW</option><option>INVESTIGATING</option><option>RESOLVED</option><option>FALSE_POSITIVE</option></select><button className="investigate" onClick={() => setToast('Alert status updated for analyst review')}>Open investigation <ChevronRight size={14}/></button></div>)}
        </div>
        <div className="footer-note"><CheckCircle2 size={14}/> All systems operational <span>·</span> Synthetic data mode <span>·</span> Last updated just now</div>
      </div>
      {toast && <div className="toast"><CheckCircle2 size={16}/> {toast}</div>}
    </section>
  </main>
}
